package com.example.duplicatetable.service;


import jakarta.persistence.EntityManager;
import jakarta.persistence.PersistenceContext;
import jakarta.transaction.Transactional;
import org.springframework.stereotype.Service;

@Service
public class DuplicateTableService {

    @PersistenceContext
    private EntityManager entityManager;

    @Transactional
    public void duplicateTable(String sourceTable, String targetTable) {
        String dropQuery = "DROP TABLE IF EXISTS " + targetTable;
        String createQuery = "CREATE TABLE " + targetTable + " AS TABLE " + sourceTable;
        String q0 = "CREATE TABLE merit_listp12 ( Srno INTEGER,Rollno VARCHAR(20), cname VARCHAR(100), Category VARCHAR(20),prefer1 VARCHAR(20),prefer2 VARCHAR(20))";
//        String q1 = "INSERT INTO merit_list (Srno,Rollno,cname,Category,prefer1,prefer2)  VALUES (1, '24133045', 'SAKORKAR SHARANNYA', 'Open', 'cse', 'aiml')";
//        String q2 = "INSERT INTO merit_list (Srno,Rollno,cname,Category,prefer1,prefer2)  VALUES (2, '24234277', 'DIWAN PRERANA SUNIL', 'Open', 'cse', 'ect');";

        entityManager.createNativeQuery(q0).executeUpdate();
//        entityManager.createNativeQuery(q1).executeUpdate();
//        entityManager.createNativeQuery(q2).executeUpdate();

        entityManager.createNativeQuery(dropQuery).executeUpdate();
        entityManager.createNativeQuery(createQuery).executeUpdate();

        String q2 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2) VALUES (1, '24133045', 'SAKORKAR SHARANNYA', 'Open', 'cse', 'aiml')";
        entityManager.createNativeQuery(q2).executeUpdate();
        String q4 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2) VALUES (2, '24234277', 'DIWAN PRERANA SUNIL', 'Open', 'cse', 'ect')";
        entityManager.createNativeQuery(q4).executeUpdate();
//        String q5 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q5).executeUpdate();
//        String q6 = "VALUES (3, '24182475', 'BYADGI PUSHKAR VINAY', 'SC', 'mech', 'ect')";
//        entityManager.createNativeQuery(q6).executeUpdate();
//        String q7 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q7).executeUpdate();
//        String q8 = "VALUES (4, '24148455', 'MOKSH NIMESH PATEL', 'SC', 'cse', 'ect')";
//        entityManager.createNativeQuery(q8).executeUpdate();
//        String q9 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q9).executeUpdate();
//        String q10 = "VALUES (5, '24153437', 'SAGAR ANKITA ASHOK', 'SC', 'cse', 'ect')";
//        entityManager.createNativeQuery(q10).executeUpdate();
//        String q11 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q11).executeUpdate();
//        String q12 = "VALUES (6, '24109582', 'GUPTA HARSHVARDHAN NAVENDU', 'SC', 'cse', 'cse')";
//        entityManager.createNativeQuery(q12).executeUpdate();
//        String q13 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q13).executeUpdate();
//        String q14 = "VALUES (7, '24180444', 'SAMRUDDHI SUDHAKAR OMBASE', 'NTC', 'cse', 'ect')";
//        entityManager.createNativeQuery(q14).executeUpdate();
//        String q15 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q15).executeUpdate();
//        String q16 = "VALUES (8, '24232199', 'SHAH VANSHIKA SACHINKUMAR', 'SC', 'cse', 'ect')";
//        entityManager.createNativeQuery(q16).executeUpdate();
//        String q17 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q17).executeUpdate();
//        String q18 = "VALUES (9, '24188835', 'PRANAV ARORA', 'Open', 'cse', 'ect')";
//        entityManager.createNativeQuery(q18).executeUpdate();
//        String q19 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q19).executeUpdate();
//        String q20 = "VALUES (10, '24138003', 'BHURE ARYAN DATTATRAY', 'OBC', 'mech', 'ect')";
//        entityManager.createNativeQuery(q20).executeUpdate();
//        String q21 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q21).executeUpdate();
//        String q22 = "VALUES (11, '24122197', 'SONI MADHAV PAWANKUMAR', 'ST', 'cse', 'ect')";
//        entityManager.createNativeQuery(q22).executeUpdate();
//        String q23 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q23).executeUpdate();
//        String q24 = "VALUES (12, '24187372', 'GAWAND PRANAV TANAJI', 'NTC', 'cse', 'ect')";
//        entityManager.createNativeQuery(q24).executeUpdate();
//        String q25 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q25).executeUpdate();
//        String q26 = "VALUES (13, '24142634', 'AKSHAT TIKARIA', 'ST', 'mech', 'ect')";
//        entityManager.createNativeQuery(q26).executeUpdate();
//        String q27 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q27).executeUpdate();
//        String q28 = "VALUES (14, '24248558', 'MAHALLE OM VILAS', 'OBC', 'cse', 'ect')";
//        entityManager.createNativeQuery(q28).executeUpdate();
//        String q29 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q29).executeUpdate();
//        String q30 = "VALUES (15, '24155293', 'DETHE VED CHANDRASHEKHAR', 'OBC', 'cse', 'ect')";
//        entityManager.createNativeQuery(q30).executeUpdate();
//        String q31 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q31).executeUpdate();
//        String q32 = "VALUES (16, '24180600', 'CHINMAY DATTAPRASAD GHATE', 'ST', 'mech', 'ect')";
//        entityManager.createNativeQuery(q32).executeUpdate();
//        String q33 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q33).executeUpdate();
//        String q34 = "VALUES (17, '24284644', 'MAHESHWARY ANANT PRASHANT', 'ST', 'cse', 'ect')";
//        entityManager.createNativeQuery(q34).executeUpdate();
//        String q35 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q35).executeUpdate();
//        String q36 = "VALUES (18, '24247858', 'KALE UDAY GANESH', 'ST', 'cse', 'ect')";
//        entityManager.createNativeQuery(q36).executeUpdate();
//        String q37 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q37).executeUpdate();
//        String q38 = "VALUES (19, '24128986', 'PUJARI VEDANT ASHOK', 'NTC', 'cse', 'aiml')";
//        entityManager.createNativeQuery(q38).executeUpdate();
//        String q39 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q39).executeUpdate();
//        String q40 = "VALUES (20, '24239161', 'CHOUHAN SUYANSH ARVINDKUMAR', 'ST', 'mech', 'ect')";
//        entityManager.createNativeQuery(q40).executeUpdate();
//        String q41 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q41).executeUpdate();
//        String q42 = "VALUES (21, '24213808', 'SHIMPI MANDAR SANDIP', 'OBC', 'cse', 'ect')";
//        entityManager.createNativeQuery(q42).executeUpdate();
//        String q43 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q43).executeUpdate();
//        String q44 = "VALUES (22, '24140600', 'GAIKWAD YUVRAJ YASHWANT', 'ST', 'cse', 'ect')";
//        entityManager.createNativeQuery(q44).executeUpdate();
//        String q45 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q45).executeUpdate();
//        String q46 = "VALUES (23, '24216328', 'ANIRUDH ARVIND MAHAPATRA', 'ST', 'mech', 'ect')";
//        entityManager.createNativeQuery(q46).executeUpdate();
//        String q47 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q47).executeUpdate();
//        String q48 = "VALUES (24, '24143166', 'SAWANT ASHANI SANJAY', 'Open', 'cse', 'ect')";
//        entityManager.createNativeQuery(q48).executeUpdate();
//        String q49 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q49).executeUpdate();
//        String q50 = "VALUES (25, '24140840', 'RANDIVE RIDDHESH KALIDAS', 'OBC', 'cse', 'ect')";
//        entityManager.createNativeQuery(q50).executeUpdate();
//        String q51 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q51).executeUpdate();
//        String q52 = "VALUES (26, '24180556', 'PRAJAPATI JENIL NILESH', 'Open', 'cse', 'ect')";
//        entityManager.createNativeQuery(q52).executeUpdate();
//        String q53 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q53).executeUpdate();
//        String q54 = "VALUES (27, '24136441', 'SHREYASH CHANDRA', 'Open', 'cse', 'aiml')";
//        entityManager.createNativeQuery(q54).executeUpdate();
//        String q55 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q55).executeUpdate();
//        String q56 = "VALUES (28, '24171047', 'MULWANI KRISH NARESH', 'Open', 'cse', 'ect')";
//        entityManager.createNativeQuery(q56).executeUpdate();
//        String q57 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q57).executeUpdate();
//        String q58 = "VALUES (29, '24174889', 'GANDHEWAR SWAYAM PARAG', 'Open', 'cse', 'ect')";
//        entityManager.createNativeQuery(q58).executeUpdate();
//        String q59 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q59).executeUpdate();
//        String q60 = "VALUES (30, '24121814', 'UTKARSH GUPTA', 'Open', 'cse', 'ect')";
//        entityManager.createNativeQuery(q60).executeUpdate();
//        String q61 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q61).executeUpdate();
//        String q62 = "VALUES (31, '24182021', 'KATDARE KAIVALYA GIRISH', 'Open', 'cse', 'ect')";
//        entityManager.createNativeQuery(q62).executeUpdate();
//        String q63 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q63).executeUpdate();
//        String q64 = "VALUES (32, '24140393', 'DALAL JINANSH PUNITKUMAR', 'Open', 'cse', 'ect')";
//        entityManager.createNativeQuery(q64).executeUpdate();
//        String q65 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q65).executeUpdate();
//        String q66 = "VALUES (33, '24146673', 'BHATTAD PRANAV HEMANT', 'Open', 'mech', 'ect')";
//        entityManager.createNativeQuery(q66).executeUpdate();
//        String q67 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q67).executeUpdate();
//        String q68 = "VALUES (34, '24138347', 'MORE PRAJWAL PRAMOD', 'OBC', 'cse', 'ect')";
//        entityManager.createNativeQuery(q68).executeUpdate();
//        String q69 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q69).executeUpdate();
//        String q70 = "VALUES (35, '24217471', 'WADKILE TUSHAR RAOSAHEB', 'Open', 'cse', 'ect')";
//        entityManager.createNativeQuery(q70).executeUpdate();
//        String q71 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q71).executeUpdate();
//        String q72 = "VALUES (36, '24114837', 'JAMDAR JIBRAN JAVED', 'Open', 'cse', 'cse')";
//        entityManager.createNativeQuery(q72).executeUpdate();
//        String q73 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q73).executeUpdate();
//        String q74 = "VALUES (37, '24138682', 'HAJARNIS INDRANEEL AMOL', 'Open', 'cse', 'ect')";
//        entityManager.createNativeQuery(q74).executeUpdate();
//        String q75 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q75).executeUpdate();
//        String q76 = "VALUES (38, '24137219', 'JADHAV MANTHAN BHARAT', 'NTC', 'cse', 'ect')";
//        entityManager.createNativeQuery(q76).executeUpdate();
//        String q77 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q77).executeUpdate();
//        String q78 = "VALUES (39, '24270587', 'BADHE VAISHNAVI AMOL', 'Open', 'mech', 'ect')";
//        entityManager.createNativeQuery(q78).executeUpdate();
//        String q79 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q79).executeUpdate();
//        String q80 = "VALUES (40, '24240356', 'DESHMUKH YASH SUNIL', 'OBC', 'cse', 'ect')";
//        entityManager.createNativeQuery(q80).executeUpdate();
//        String q81 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q81).executeUpdate();
//        String q82 = "VALUES (41, '24274745', 'AGARWAL SIDDHANT LALIT', 'Open', 'mech', 'ect')";
//        entityManager.createNativeQuery(q82).executeUpdate();
//        String q83 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q83).executeUpdate();
//        String q84 = "VALUES (42, '24299270', 'NACHAN YASH DNYANDEV', 'NTC', 'cse', 'ect')";
//        entityManager.createNativeQuery(q84).executeUpdate();
//        String q85 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q85).executeUpdate();
//        String q86 = "VALUES (43, '24135545', 'SHINDE HARSHWARDHAN YUVARAJ', 'Open', 'cse', 'aiml')";
//        entityManager.createNativeQuery(q86).executeUpdate();
//        String q87 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q87).executeUpdate();
//        String q88 = "VALUES (44, '24137438', 'SONAWANE PRACHI PRAMOD', 'OBC', 'cse', 'ect')";
//        entityManager.createNativeQuery(q88).executeUpdate();
//        String q89 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q89).executeUpdate();
//        String q90 = "VALUES (45, '24237781', 'ISHAAN SAMEER SARDESHMUKH', 'Open', 'cse', 'ect')";
//        entityManager.createNativeQuery(q90).executeUpdate();
//        String q91 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q91).executeUpdate();
//        String q92 = "VALUES (46, '24214884', 'KARAMBALKAR HARSH JITIN', 'Open', 'cse', 'ect')";
//        entityManager.createNativeQuery(q92).executeUpdate();
//        String q93 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q93).executeUpdate();
//        String q94 = "VALUES (47, '24102832', 'MOHIT VIVEK JAIN', 'Open', 'cse', 'cse')";
//        entityManager.createNativeQuery(q94).executeUpdate();
//        String q95 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q95).executeUpdate();
//        String q96 = "VALUES (48, '24199852', 'PASARE SARVESH DATTATRAY', 'Open', 'cse', 'ect')";
//        entityManager.createNativeQuery(q96).executeUpdate();
//        String q97 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q97).executeUpdate();
//        String q98 = "VALUES (49, '24180314', 'AHUJA KARAN SANJAY', 'Open', 'mech', 'ect')";
//        entityManager.createNativeQuery(q98).executeUpdate();
//        String q99 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q99).executeUpdate();
//        String q100 = "VALUES (50, '24301030', 'LABHSHETWAR SOHAM LAXMIKANT', 'Open', 'cse', 'ect')";
//        entityManager.createNativeQuery(q100).executeUpdate();
//        String q101 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q101).executeUpdate();
//        String q102 = "VALUES (51, '24141393', 'KOTHALKAR YASH ANKUR', 'Open', 'cse', 'ect')";
//        entityManager.createNativeQuery(q102).executeUpdate();
//        String q103 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q103).executeUpdate();
//        String q104 = "VALUES (52, '24115323', 'WAGHMARE JAYESH SANJAY', 'OBC', 'cse', 'cse')";
//        entityManager.createNativeQuery(q104).executeUpdate();
//        String q105 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q105).executeUpdate();
//        String q106 = "VALUES (53, '24210161', 'PHARTADE DNYANESHWARI ANIL', 'OBC', 'cse', 'ect')";
//        entityManager.createNativeQuery(q106).executeUpdate();
//        String q107 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q107).executeUpdate();
//        String q108 = "VALUES (54, '24133049', 'SAKORKAR SHARANNYA', 'Open', 'cse', 'aiml')";
//        entityManager.createNativeQuery(q108).executeUpdate();
//        String q109 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q109).executeUpdate();
//        String q110 = "VALUES (55, '24234281', 'DIWAN PRERANA SUNIL', 'Open', 'cse', 'ect')";
//        entityManager.createNativeQuery(q110).executeUpdate();
//        String q111 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q111).executeUpdate();
//        String q112 = "VALUES (56, '24182479', 'BYADGI PUSHKAR VINAY', 'SC', 'mech', 'ect')";
//        entityManager.createNativeQuery(q112).executeUpdate();
//        String q113 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q113).executeUpdate();
//        String q114 = "VALUES (57, '24148459', 'MOKSH NIMESH PATEL', 'SC', 'cse', 'ect')";
//        entityManager.createNativeQuery(q114).executeUpdate();
//        String q115 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q115).executeUpdate();
//        String q116 = "VALUES (58, '24153441', 'SAGAR ANKITA ASHOK', 'SC', 'cse', 'ect')";
//        entityManager.createNativeQuery(q116).executeUpdate();
//        String q117 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q117).executeUpdate();
//        String q118 = "VALUES (59, '24109586', 'GUPTA HARSHVARDHAN NAVENDU', 'SC', 'cse', 'cse')";
//        entityManager.createNativeQuery(q118).executeUpdate();
//        String q119 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q119).executeUpdate();
//        String q120 = "VALUES (60, '24180448', 'SAMRUDDHI SUDHAKAR OMBASE', 'NTC', 'cse', 'ect')";
//        entityManager.createNativeQuery(q120).executeUpdate();
//        String q121 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q121).executeUpdate();
//        String q122 = "VALUES (61, '24232203', 'SHAH VANSHIKA SACHINKUMAR', 'SC', 'cse', 'ect')";
//        entityManager.createNativeQuery(q122).executeUpdate();
//        String q123 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q123).executeUpdate();
//        String q124 = "VALUES (62, '24188839', 'PRANAV ARORA', 'Open', 'cse', 'ect')";
//        entityManager.createNativeQuery(q124).executeUpdate();
//        String q125 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q125).executeUpdate();
//        String q126 = "VALUES (63, '24138007', 'BHURE ARYAN DATTATRAY', 'OBC', 'mech', 'ect')";
//        entityManager.createNativeQuery(q126).executeUpdate();
//        String q127 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q127).executeUpdate();
//        String q128 = "VALUES (64, '24122201', 'SONI MADHAV PAWANKUMAR', 'ST', 'cse', 'ect')";
//        entityManager.createNativeQuery(q128).executeUpdate();
//        String q129 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q129).executeUpdate();
//        String q130 = "VALUES (65, '24187376', 'GAWAND PRANAV TANAJI', 'NTC', 'cse', 'ect')";
//        entityManager.createNativeQuery(q130).executeUpdate();
//        String q131 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q131).executeUpdate();
//        String q132 = "VALUES (66, '24142638', 'AKSHAT TIKARIA', 'ST', 'mech', 'ect')";
//        entityManager.createNativeQuery(q132).executeUpdate();
//        String q133 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q133).executeUpdate();
//        String q134 = "VALUES (67, '24248562', 'MAHALLE OM VILAS', 'OBC', 'cse', 'ect')";
//        entityManager.createNativeQuery(q134).executeUpdate();
//        String q135 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q135).executeUpdate();
//        String q136 = "VALUES (68, '24155297', 'DETHE VED CHANDRASHEKHAR', 'OBC', 'cse', 'ect')";
//        entityManager.createNativeQuery(q136).executeUpdate();
//        String q137 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q137).executeUpdate();
//        String q138 = "VALUES (69, '24180604', 'CHINMAY DATTAPRASAD GHATE', 'ST', 'mech', 'ect')";
//        entityManager.createNativeQuery(q138).executeUpdate();
//        String q139 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q139).executeUpdate();
//        String q140 = "VALUES (70, '24284648', 'MAHESHWARY ANANT PRASHANT', 'ST', 'cse', 'ect')";
//        entityManager.createNativeQuery(q140).executeUpdate();
//        String q141 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q141).executeUpdate();
//        String q142 = "VALUES (71, '24247862', 'KALE UDAY GANESH', 'ST', 'cse', 'ect')";
//        entityManager.createNativeQuery(q142).executeUpdate();
//        String q143 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q143).executeUpdate();
//        String q144 = "VALUES (72, '24128990', 'PUJARI VEDANT ASHOK', 'NTC', 'cse', 'aiml')";
//        entityManager.createNativeQuery(q144).executeUpdate();
//        String q145 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q145).executeUpdate();
//        String q146 = "VALUES (73, '24239165', 'CHOUHAN SUYANSH ARVINDKUMAR', 'ST', 'cse', 'ect')";
//        entityManager.createNativeQuery(q146).executeUpdate();
//        String q147 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q147).executeUpdate();
//        String q148 = "VALUES (74, '24213812', 'SHIMPI MANDAR SANDIP', 'OBC', 'cse', 'ect')";
//        entityManager.createNativeQuery(q148).executeUpdate();
//        String q149 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q149).executeUpdate();
//        String q150 = "VALUES (75, '24140604', 'GAIKWAD YUVRAJ YASHWANT', 'ST', 'cse', 'ect')";
//        entityManager.createNativeQuery(q150).executeUpdate();
//        String q151 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q151).executeUpdate();
//        String q152 = "VALUES (76, '24216332', 'ANIRUDH ARVIND MAHAPATRA', 'ST', 'mech', 'ect')";
//        entityManager.createNativeQuery(q152).executeUpdate();
//        String q153 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q153).executeUpdate();
//        String q154 = "VALUES (77, '24143170', 'SAWANT ASHANI SANJAY', 'Open', 'cse', 'ect')";
//        entityManager.createNativeQuery(q154).executeUpdate();
//        String q155 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q155).executeUpdate();
//        String q156 = "VALUES (78, '24140844', 'RANDIVE RIDDHESH KALIDAS', 'OBC', 'cse', 'ect')";
//        entityManager.createNativeQuery(q156).executeUpdate();
//        String q157 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q157).executeUpdate();
//        String q158 = "VALUES (79, '24180560', 'PRAJAPATI JENIL NILESH', 'Open', 'cse', 'ect')";
//        entityManager.createNativeQuery(q158).executeUpdate();
//        String q159 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q159).executeUpdate();
//        String q160 = "VALUES (80, '24136445', 'SHREYASH CHANDRA', 'Open', 'cse', 'aiml')";
//        entityManager.createNativeQuery(q160).executeUpdate();
//        String q161 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q161).executeUpdate();
//        String q162 = "VALUES (81, '24171051', 'MULWANI KRISH NARESH', 'Open', 'cse', 'ect')";
//        entityManager.createNativeQuery(q162).executeUpdate();
//        String q163 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q163).executeUpdate();
//        String q164 = "VALUES (82, '24174893', 'GANDHEWAR SWAYAM PARAG', 'Open', 'cse', 'ect')";
//        entityManager.createNativeQuery(q164).executeUpdate();
//        String q165 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q165).executeUpdate();
//        String q166 = "VALUES (83, '24121818', 'UTKARSH GUPTA', 'Open', 'cse', 'ect')";
//        entityManager.createNativeQuery(q166).executeUpdate();
//        String q167 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q167).executeUpdate();
//        String q168 = "VALUES (84, '24182025', 'KATDARE KAIVALYA GIRISH', 'Open', 'cse', 'ect')";
//        entityManager.createNativeQuery(q168).executeUpdate();
//        String q169 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q169).executeUpdate();
//        String q170 = "VALUES (85, '24140397', 'DALAL JINANSH PUNITKUMAR', 'Open', 'cse', 'ect')";
//        entityManager.createNativeQuery(q170).executeUpdate();
//        String q171 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q171).executeUpdate();
//        String q172 = "VALUES (86, '24146677', 'BHATTAD PRANAV HEMANT', 'Open', 'mech', 'ect')";
//        entityManager.createNativeQuery(q172).executeUpdate();
//        String q173 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q173).executeUpdate();
//        String q174 = "VALUES (87, '24138351', 'MORE PRAJWAL PRAMOD', 'OBC', 'cse', 'ect')";
//        entityManager.createNativeQuery(q174).executeUpdate();
//        String q175 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q175).executeUpdate();
//        String q176 = "VALUES (88, '24217475', 'WADKILE TUSHAR RAOSAHEB', 'Open', 'cse', 'ect')";
//        entityManager.createNativeQuery(q176).executeUpdate();
//        String q177 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q177).executeUpdate();
//        String q178 = "VALUES (89, '24114841', 'JAMDAR JIBRAN JAVED', 'Open', 'cse', 'cse')";
//        entityManager.createNativeQuery(q178).executeUpdate();
//        String q179 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q179).executeUpdate();
//        String q180 = "VALUES (90, '24138686', 'HAJARNIS INDRANEEL AMOL', 'Open', 'cse', 'ect')";
//        entityManager.createNativeQuery(q180).executeUpdate();
//        String q181 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q181).executeUpdate();
//        String q182 = "VALUES (91, '24137223', 'JADHAV MANTHAN BHARAT', 'NTC', 'cse', 'ect')";
//        entityManager.createNativeQuery(q182).executeUpdate();
//        String q183 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q183).executeUpdate();
//        String q184 = "VALUES (92, '24270591', 'BADHE VAISHNAVI AMOL', 'Open', 'mech', 'ect')";
//        entityManager.createNativeQuery(q184).executeUpdate();
//        String q185 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q185).executeUpdate();
//        String q186 = "VALUES (93, '24240360', 'DESHMUKH YASH SUNIL', 'OBC', 'cse', 'ect')";
//        entityManager.createNativeQuery(q186).executeUpdate();
//        String q187 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q187).executeUpdate();
//        String q188 = "VALUES (94, '24274749', 'AGARWAL SIDDHANT LALIT', 'Open', 'mech', 'ect')";
//        entityManager.createNativeQuery(q188).executeUpdate();
//        String q189 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q189).executeUpdate();
//        String q190 = "VALUES (95, '24299274', 'NACHAN YASH DNYANDEV', 'NTC', 'cse', 'ect')";
//        entityManager.createNativeQuery(q190).executeUpdate();
//        String q191 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q191).executeUpdate();
//        String q192 = "VALUES (96, '24135549', 'SHINDE HARSHWARDHAN YUVARAJ', 'Open', 'cse', 'aiml')";
//        entityManager.createNativeQuery(q192).executeUpdate();
//        String q193 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q193).executeUpdate();
//        String q194 = "VALUES (97, '24137442', 'SONAWANE PRACHI PRAMOD', 'OBC', 'cse', 'ect')";
//        entityManager.createNativeQuery(q194).executeUpdate();
//        String q195 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q195).executeUpdate();
//        String q196 = "VALUES (98, '24237785', 'ISHAAN SAMEER SARDESHMUKH', 'Open', 'cse', 'ect')";
//        entityManager.createNativeQuery(q196).executeUpdate();
//        String q197 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q197).executeUpdate();
//        String q198 = "VALUES (99, '24214888', 'KARAMBALKAR HARSH JITIN', 'Open', 'cse', 'ect')";
//        entityManager.createNativeQuery(q198).executeUpdate();
//        String q199 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q199).executeUpdate();
//        String q200 = "VALUES (100, '24102836', 'MOHIT VIVEK JAIN', 'Open', 'cse', 'cse')";
//        entityManager.createNativeQuery(q200).executeUpdate();
//        String q201 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q201).executeUpdate();
//        String q202 = "VALUES (101, '24199856', 'PASARE SARVESH DATTATRAY', 'Open', 'cse', 'ect')";
//        entityManager.createNativeQuery(q202).executeUpdate();
//        String q203 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q203).executeUpdate();
//        String q204 = "VALUES (102, '24180318', 'AHUJA KARAN SANJAY', 'Open', 'mech', 'ect')";
//        entityManager.createNativeQuery(q204).executeUpdate();
//        String q205 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q205).executeUpdate();
//        String q206 = "VALUES (103, '24301034', 'LABHSHETWAR SOHAM LAXMIKANT', 'Open', 'cse', 'ect')";
//        entityManager.createNativeQuery(q206).executeUpdate();
//        String q207 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q207).executeUpdate();
//        String q208 = "VALUES (104, '24141397', 'KOTHALKAR YASH ANKUR', 'Open', 'cse', 'ect')";
//        entityManager.createNativeQuery(q208).executeUpdate();
//        String q209 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q209).executeUpdate();
//        String q210 = "VALUES (105, '24115327', 'WAGHMARE JAYESH SANJAY', 'OBC', 'cse', 'cse')";
//        entityManager.createNativeQuery(q210).executeUpdate();
//        String q211 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q211).executeUpdate();
//        String q212 = "VALUES (106, '24210165', 'PHARTADE DNYANESHWARI ANIL', 'OBC', 'cse', 'ect')";
//        entityManager.createNativeQuery(q212).executeUpdate();
//        String q213 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q213).executeUpdate();
//        String q214 = "VALUES (107, '24133053', 'SAKORKAR SHARANNYA', 'Open', 'cse', 'aiml')";
//        entityManager.createNativeQuery(q214).executeUpdate();
//        String q215 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q215).executeUpdate();
//        String q216 = "VALUES (108, '24234285', 'DIWAN PRERANA SUNIL', 'Open', 'cse', 'ect')";
//        entityManager.createNativeQuery(q216).executeUpdate();
//        String q217 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q217).executeUpdate();
//        String q218 = "VALUES (109, '24182483', 'BYADGI PUSHKAR VINAY', 'SC', 'mech', 'ect')";
//        entityManager.createNativeQuery(q218).executeUpdate();
//        String q219 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q219).executeUpdate();
//        String q220 = "VALUES (110, '24148463', 'MOKSH NIMESH PATEL', 'SC', 'cse', 'ect')";
//        entityManager.createNativeQuery(q220).executeUpdate();
//        String q221 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q221).executeUpdate();
//        String q222 = "VALUES (111, '24153445', 'SAGAR ANKITA ASHOK', 'SC', 'cse', 'ect')";
//        entityManager.createNativeQuery(q222).executeUpdate();
//        String q223 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q223).executeUpdate();
//        String q224 = "VALUES (112, '24109590', 'GUPTA HARSHVARDHAN NAVENDU', 'SC', 'cse', 'cse')";
//        entityManager.createNativeQuery(q224).executeUpdate();
//        String q225 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q225).executeUpdate();
//        String q226 = "VALUES (113, '24180452', 'SAMRUDDHI SUDHAKAR OMBASE', 'NTC', 'cse', 'ect')";
//        entityManager.createNativeQuery(q226).executeUpdate();
//        String q227 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q227).executeUpdate();
//        String q228 = "VALUES (114, '24232207', 'SHAH VANSHIKA SACHINKUMAR', 'SC', 'cse', 'ect')";
//        entityManager.createNativeQuery(q228).executeUpdate();
//        String q229 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q229).executeUpdate();
//        String q230 = "VALUES (115, '24188843', 'PRANAV ARORA', 'Open', 'cse', 'ect')";
//        entityManager.createNativeQuery(q230).executeUpdate();
//        String q231 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q231).executeUpdate();
//        String q232 = "VALUES (116, '24138011', 'BHURE ARYAN DATTATRAY', 'OBC', 'mech', 'ect')";
//        entityManager.createNativeQuery(q232).executeUpdate();
//        String q233 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q233).executeUpdate();
//        String q234 = "VALUES (117, '24122205', 'SONI MADHAV PAWANKUMAR', 'ST', 'cse', 'ect')";
//        entityManager.createNativeQuery(q234).executeUpdate();
//        String q235 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q235).executeUpdate();
//        String q236 = "VALUES (118, '24187380', 'GAWAND PRANAV TANAJI', 'NTC', 'cse', 'ect')";
//        entityManager.createNativeQuery(q236).executeUpdate();
//        String q237 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q237).executeUpdate();
//        String q238 = "VALUES (119, '24142642', 'AKSHAT TIKARIA', 'ST', 'mech', 'ect')";
//        entityManager.createNativeQuery(q238).executeUpdate();
//        String q239 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q239).executeUpdate();
//        String q240 = "VALUES (120, '24248566', 'MAHALLE OM VILAS', 'OBC', 'cse', 'ect')";
//        entityManager.createNativeQuery(q240).executeUpdate();
//        String q241 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q241).executeUpdate();
//        String q242 = "VALUES (121, '24155301', 'DETHE VED CHANDRASHEKHAR', 'OBC', 'cse', 'ect')";
//        entityManager.createNativeQuery(q242).executeUpdate();
//        String q243 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q243).executeUpdate();
//        String q244 = "VALUES (122, '24180608', 'CHINMAY DATTAPRASAD GHATE', 'ST', 'mech', 'ect')";
//        entityManager.createNativeQuery(q244).executeUpdate();
//        String q245 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q245).executeUpdate();
//        String q246 = "VALUES (123, '24284652', 'MAHESHWARY ANANT PRASHANT', 'ST', 'cse', 'ect')";
//        entityManager.createNativeQuery(q246).executeUpdate();
//        String q247 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q247).executeUpdate();
//        String q248 = "VALUES (124, '24247866', 'KALE UDAY GANESH', 'ST', 'cse', 'ect')";
//        entityManager.createNativeQuery(q248).executeUpdate();
//        String q249 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q249).executeUpdate();
//        String q250 = "VALUES (125, '24128994', 'PUJARI VEDANT ASHOK', 'NTC', 'cse', 'aiml')";
//        entityManager.createNativeQuery(q250).executeUpdate();
//        String q251 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q251).executeUpdate();
//        String q252 = "VALUES (126, '24239169', 'CHOUHAN SUYANSH ARVINDKUMAR', 'ST', 'cse', 'ect')";
//        entityManager.createNativeQuery(q252).executeUpdate();
//        String q253 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q253).executeUpdate();
//        String q254 = "VALUES (127, '24213816', 'SHIMPI MANDAR SANDIP', 'OBC', 'cse', 'ect')";
//        entityManager.createNativeQuery(q254).executeUpdate();
//        String q255 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q255).executeUpdate();
//        String q256 = "VALUES (128, '24140608', 'GAIKWAD YUVRAJ YASHWANT', 'ST', 'cse', 'ect')";
//        entityManager.createNativeQuery(q256).executeUpdate();
//        String q257 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q257).executeUpdate();
//        String q258 = "VALUES (129, '24216336', 'ANIRUDH ARVIND MAHAPATRA', 'ST', 'mech', 'ect')";
//        entityManager.createNativeQuery(q258).executeUpdate();
//        String q259 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q259).executeUpdate();
//        String q260 = "VALUES (130, '24143174', 'SAWANT ASHANI SANJAY', 'Open', 'cse', 'ect')";
//        entityManager.createNativeQuery(q260).executeUpdate();
//        String q261 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q261).executeUpdate();
//        String q262 = "VALUES (131, '24140848', 'RANDIVE RIDDHESH KALIDAS', 'OBC', 'cse', 'ect')";
//        entityManager.createNativeQuery(q262).executeUpdate();
//        String q263 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q263).executeUpdate();
//        String q264 = "VALUES (132, '24180564', 'PRAJAPATI JENIL NILESH', 'Open', 'cse', 'ect')";
//        entityManager.createNativeQuery(q264).executeUpdate();
//        String q265 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q265).executeUpdate();
//        String q266 = "VALUES (133, '24136449', 'SHREYASH CHANDRA', 'Open', 'cse', 'aiml')";
//        entityManager.createNativeQuery(q266).executeUpdate();
//        String q267 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q267).executeUpdate();
//        String q268 = "VALUES (134, '24171055', 'MULWANI KRISH NARESH', 'Open', 'cse', 'ect')";
//        entityManager.createNativeQuery(q268).executeUpdate();
//        String q269 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q269).executeUpdate();
//        String q270 = "VALUES (135, '24174897', 'GANDHEWAR SWAYAM PARAG', 'Open', 'cse', 'ect')";
//        entityManager.createNativeQuery(q270).executeUpdate();
//        String q271 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q271).executeUpdate();
//        String q272 = "VALUES (136, '24121822', 'UTKARSH GUPTA', 'Open', 'cse', 'ect')";
//        entityManager.createNativeQuery(q272).executeUpdate();
//        String q273 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q273).executeUpdate();
//        String q274 = "VALUES (137, '24182029', 'KATDARE KAIVALYA GIRISH', 'Open', 'cse', 'ect')";
//        entityManager.createNativeQuery(q274).executeUpdate();
//        String q275 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q275).executeUpdate();
//        String q276 = "VALUES (138, '24140401', 'DALAL JINANSH PUNITKUMAR', 'Open', 'cse', 'ect')";
//        entityManager.createNativeQuery(q276).executeUpdate();
//        String q277 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q277).executeUpdate();
//        String q278 = "VALUES (139, '24146681', 'BHATTAD PRANAV HEMANT', 'Open', 'mech', 'ect')";
//        entityManager.createNativeQuery(q278).executeUpdate();
//        String q279 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q279).executeUpdate();
//        String q280 = "VALUES (140, '24138355', 'MORE PRAJWAL PRAMOD', 'OBC', 'cse', 'ect')";
//        entityManager.createNativeQuery(q280).executeUpdate();
//        String q281 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q281).executeUpdate();
//        String q282 = "VALUES (141, '24217479', 'WADKILE TUSHAR RAOSAHEB', 'Open', 'cse', 'ect')";
//        entityManager.createNativeQuery(q282).executeUpdate();
//        String q283 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q283).executeUpdate();
//        String q284 = "VALUES (142, '24114845', 'JAMDAR JIBRAN JAVED', 'Open', 'cse', 'cse')";
//        entityManager.createNativeQuery(q284).executeUpdate();
//        String q285 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q285).executeUpdate();
//        String q286 = "VALUES (143, '24138690', 'HAJARNIS INDRANEEL AMOL', 'Open', 'cse', 'ect')";
//        entityManager.createNativeQuery(q286).executeUpdate();
//        String q287 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q287).executeUpdate();
//        String q288 = "VALUES (144, '24137227', 'JADHAV MANTHAN BHARAT', 'NTC', 'cse', 'ect')";
//        entityManager.createNativeQuery(q288).executeUpdate();
//        String q289 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q289).executeUpdate();
//        String q290 = "VALUES (145, '24270595', 'BADHE VAISHNAVI AMOL', 'Open', 'mech', 'ect')";
//        entityManager.createNativeQuery(q290).executeUpdate();
//        String q291 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q291).executeUpdate();
//        String q292 = "VALUES (146, '24240364', 'DESHMUKH YASH SUNIL', 'OBC', 'cse', 'ect')";
//        entityManager.createNativeQuery(q292).executeUpdate();
//        String q293 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q293).executeUpdate();
//        String q294 = "VALUES (147, '24274753', 'AGARWAL SIDDHANT LALIT', 'Open', 'mech', 'ect')";
//        entityManager.createNativeQuery(q294).executeUpdate();
//        String q295 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q295).executeUpdate();
//        String q296 = "VALUES (148, '24299278', 'NACHAN YASH DNYANDEV', 'NTC', 'cse', 'ect')";
//        entityManager.createNativeQuery(q296).executeUpdate();
//        String q297 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q297).executeUpdate();
//        String q298 = "VALUES (149, '24135553', 'SHINDE HARSHWARDHAN YUVARAJ', 'Open', 'cse', 'aiml')";
//        entityManager.createNativeQuery(q298).executeUpdate();
//        String q299 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q299).executeUpdate();
//        String q300 = "VALUES (150, '24137446', 'SONAWANE PRACHI PRAMOD', 'OBC', 'cse', 'ect')";
//        entityManager.createNativeQuery(q300).executeUpdate();
//        String q301 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q301).executeUpdate();
//        String q302 = "VALUES (151, '24237789', 'ISHAAN SAMEER SARDESHMUKH', 'Open', 'cse', 'ect')";
//        entityManager.createNativeQuery(q302).executeUpdate();
//        String q303 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q303).executeUpdate();
//        String q304 = "VALUES (152, '24214892', 'KARAMBALKAR HARSH JITIN', 'Open', 'cse', 'ect')";
//        entityManager.createNativeQuery(q304).executeUpdate();
//        String q305 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q305).executeUpdate();
//        String q306 = "VALUES (153, '24102840', 'MOHIT VIVEK JAIN', 'Open', 'cse', 'cse')";
//        entityManager.createNativeQuery(q306).executeUpdate();
//        String q307 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q307).executeUpdate();
//        String q308 = "VALUES (154, '24199860', 'PASARE SARVESH DATTATRAY', 'Open', 'cse', 'ect')";
//        entityManager.createNativeQuery(q308).executeUpdate();
//        String q309 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q309).executeUpdate();
//        String q310 = "VALUES (155, '24180322', 'AHUJA KARAN SANJAY', 'Open', 'mech', 'ect')";
//        entityManager.createNativeQuery(q310).executeUpdate();
//        String q311 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q311).executeUpdate();
//        String q312 = "VALUES (156, '24301038', 'LABHSHETWAR SOHAM LAXMIKANT', 'Open', 'cse', 'ect')";
//        entityManager.createNativeQuery(q312).executeUpdate();
//        String q313 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q313).executeUpdate();
//        String q314 = "VALUES (157, '24141401', 'KOTHALKAR YASH ANKUR', 'Open', 'cse', 'ect')";
//        entityManager.createNativeQuery(q314).executeUpdate();
//        String q315 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q315).executeUpdate();
//        String q316 = "VALUES (158, '24115331', 'WAGHMARE JAYESH SANJAY', 'OBC', 'cse', 'cse')";
//        entityManager.createNativeQuery(q316).executeUpdate();
//        String q317 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q317).executeUpdate();
//        String q318 = "VALUES (159, '24210169', 'PHARTADE DNYANESHWARI ANIL', 'OBC', 'cse', 'ect')";
//        entityManager.createNativeQuery(q318).executeUpdate();
//        String q319 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q319).executeUpdate();
//        String q320 = "VALUES (160, '24133057', 'SAKORKAR SHARANNYA', 'Open', 'cse', 'aiml')";
//        entityManager.createNativeQuery(q320).executeUpdate();
//        String q321 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q321).executeUpdate();
//        String q322 = "VALUES (161, '24234289', 'DIWAN PRERANA SUNIL', 'Open', 'cse', 'ect')";
//        entityManager.createNativeQuery(q322).executeUpdate();
//        String q323 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q323).executeUpdate();
//        String q324 = "VALUES (162, '24182487', 'BYADGI PUSHKAR VINAY', 'SC', 'mech', 'ect')";
//        entityManager.createNativeQuery(q324).executeUpdate();
//        String q325 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q325).executeUpdate();
//        String q326 = "VALUES (163, '24148467', 'MOKSH NIMESH PATEL', 'SC', 'cse', 'ect')";
//        entityManager.createNativeQuery(q326).executeUpdate();
//        String q327 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q327).executeUpdate();
//        String q328 = "VALUES (164, '24153449', 'SAGAR ANKITA ASHOK', 'SC', 'cse', 'ect')";
//        entityManager.createNativeQuery(q328).executeUpdate();
//        String q329 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q329).executeUpdate();
//        String q330 = "VALUES (165, '24109594', 'GUPTA HARSHVARDHAN NAVENDU', 'SC', 'cse', 'cse')";
//        entityManager.createNativeQuery(q330).executeUpdate();
//        String q331 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q331).executeUpdate();
//        String q332 = "VALUES (166, '24180456', 'SAMRUDDHI SUDHAKAR OMBASE', 'NTC', 'cse', 'ect')";
//        entityManager.createNativeQuery(q332).executeUpdate();
//        String q333 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q333).executeUpdate();
//        String q334 = "VALUES (167, '24232211', 'SHAH VANSHIKA SACHINKUMAR', 'SC', 'cse', 'ect')";
//        entityManager.createNativeQuery(q334).executeUpdate();
//        String q335 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q335).executeUpdate();
//        String q336 = "VALUES (168, '24188847', 'PRANAV ARORA', 'Open', 'cse', 'ect')";
//        entityManager.createNativeQuery(q336).executeUpdate();
//        String q337 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q337).executeUpdate();
//        String q338 = "VALUES (169, '24138015', 'BHURE ARYAN DATTATRAY', 'OBC', 'mech', 'ect')";
//        entityManager.createNativeQuery(q338).executeUpdate();
//        String q339 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q339).executeUpdate();
//        String q340 = "VALUES (170, '24122209', 'SONI MADHAV PAWANKUMAR', 'ST', 'cse', 'aiml')";
//        entityManager.createNativeQuery(q340).executeUpdate();
//        String q341 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q341).executeUpdate();
//        String q342 = "VALUES (171, '24187384', 'GAWAND PRANAV TANAJI', 'NTC', 'cse', 'ect')";
//        entityManager.createNativeQuery(q342).executeUpdate();
//        String q343 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q343).executeUpdate();
//        String q344 = "VALUES (172, '24142646', 'AKSHAT TIKARIA', 'ST', 'mech', 'ect')";
//        entityManager.createNativeQuery(q344).executeUpdate();
//        String q345 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q345).executeUpdate();
//        String q346 = "VALUES (173, '24248570', 'MAHALLE OM VILAS', 'OBC', 'cse', 'ect')";
//        entityManager.createNativeQuery(q346).executeUpdate();
//        String q347 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q347).executeUpdate();
//        String q348 = "VALUES (174, '24155305', 'DETHE VED CHANDRASHEKHAR', 'OBC', 'cse', 'ect')";
//        entityManager.createNativeQuery(q348).executeUpdate();
//        String q349 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q349).executeUpdate();
//        String q350 = "VALUES (175, '24180612', 'CHINMAY DATTAPRASAD GHATE', 'ST', 'mech', 'ect')";
//        entityManager.createNativeQuery(q350).executeUpdate();
//        String q351 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q351).executeUpdate();
//        String q352 = "VALUES (176, '24284656', 'MAHESHWARY ANANT PRASHANT', 'ST', 'cse', 'ect')";
//        entityManager.createNativeQuery(q352).executeUpdate();
//        String q353 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q353).executeUpdate();
//        String q354 = "VALUES (177, '24247870', 'KALE UDAY GANESH', 'ST', 'cse', 'ect')";
//        entityManager.createNativeQuery(q354).executeUpdate();
//        String q355 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q355).executeUpdate();
//        String q356 = "VALUES (178, '24128998', 'PUJARI VEDANT ASHOK', 'NTC', 'cse', 'aiml')";
//        entityManager.createNativeQuery(q356).executeUpdate();
//        String q357 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q357).executeUpdate();
//        String q358 = "VALUES (179, '24239173', 'CHOUHAN SUYANSH ARVINDKUMAR', 'ST', 'cse', 'ect')";
//        entityManager.createNativeQuery(q358).executeUpdate();
//        String q359 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q359).executeUpdate();
//        String q360 = "VALUES (180, '24213820', 'SHIMPI MANDAR SANDIP', 'OBC', 'cse', 'ect')";
//        entityManager.createNativeQuery(q360).executeUpdate();
//        String q361 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q361).executeUpdate();
//        String q362 = "VALUES (181, '24140612', 'GAIKWAD YUVRAJ YASHWANT', 'ST', 'cse', 'ect')";
//        entityManager.createNativeQuery(q362).executeUpdate();
//        String q363 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q363).executeUpdate();
//        String q364 = "VALUES (182, '24216340', 'ANIRUDH ARVIND MAHAPATRA', 'ST', 'mech', 'ect')";
//        entityManager.createNativeQuery(q364).executeUpdate();
//        String q365 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q365).executeUpdate();
//        String q366 = "VALUES (183, '24143178', 'SAWANT ASHANI SANJAY', 'Open', 'cse', 'ect')";
//        entityManager.createNativeQuery(q366).executeUpdate();
//        String q367 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q367).executeUpdate();
//        String q368 = "VALUES (184, '24140852', 'RANDIVE RIDDHESH KALIDAS', 'OBC', 'cse', 'ect')";
//        entityManager.createNativeQuery(q368).executeUpdate();
//        String q369 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q369).executeUpdate();
//        String q370 = "VALUES (185, '24180568', 'PRAJAPATI JENIL NILESH', 'Open', 'cse', 'ect')";
//        entityManager.createNativeQuery(q370).executeUpdate();
//        String q371 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q371).executeUpdate();
//        String q372 = "VALUES (186, '24136453', 'SHREYASH CHANDRA', 'Open', 'cse', 'ect')";
//        entityManager.createNativeQuery(q372).executeUpdate();
//        String q373 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q373).executeUpdate();
//        String q374 = "VALUES (187, '24171059', 'MULWANI KRISH NARESH', 'Open', 'cse', 'ect')";
//        entityManager.createNativeQuery(q374).executeUpdate();
//        String q375 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q375).executeUpdate();
//        String q376 = "VALUES (188, '24174901', 'GANDHEWAR SWAYAM PARAG', 'Open', 'cse', 'ect')";
//        entityManager.createNativeQuery(q376).executeUpdate();
//        String q377 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q377).executeUpdate();
//        String q378 = "VALUES (189, '24121826', 'UTKARSH GUPTA', 'Open', 'cse', 'ect')";
//        entityManager.createNativeQuery(q378).executeUpdate();
//        String q379 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q379).executeUpdate();
//        String q380 = "VALUES (190, '24182033', 'KATDARE KAIVALYA GIRISH', 'Open', 'cse', 'ect')";
//        entityManager.createNativeQuery(q380).executeUpdate();
//        String q381 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q381).executeUpdate();
//        String q382 = "VALUES (191, '24140405', 'DALAL JINANSH PUNITKUMAR', 'Open', 'cse', 'ect')";
//        entityManager.createNativeQuery(q382).executeUpdate();
//        String q383 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q383).executeUpdate();
//        String q384 = "VALUES (192, '24146685', 'BHATTAD PRANAV HEMANT', 'Open', 'mech', 'ect')";
//        entityManager.createNativeQuery(q384).executeUpdate();
//        String q385 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q385).executeUpdate();
//        String q386 = "VALUES (193, '24138359', 'MORE PRAJWAL PRAMOD', 'OBC', 'cse', 'ect')";
//        entityManager.createNativeQuery(q386).executeUpdate();
//        String q387 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q387).executeUpdate();
//        String q388 = "VALUES (194, '24217483', 'WADKILE TUSHAR RAOSAHEB', 'Open', 'cse', 'ect')";
//        entityManager.createNativeQuery(q388).executeUpdate();
//        String q389 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q389).executeUpdate();
//        String q390 = "VALUES (195, '24114849', 'JAMDAR JIBRAN JAVED', 'Open', 'cse', 'cse')";
//        entityManager.createNativeQuery(q390).executeUpdate();
//        String q391 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q391).executeUpdate();
//        String q392 = "VALUES (196, '24138694', 'HAJARNIS INDRANEEL AMOL', 'Open', 'cse', 'ect')";
//        entityManager.createNativeQuery(q392).executeUpdate();
//        String q393 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q393).executeUpdate();
//        String q394 = "VALUES (197, '24137231', 'JADHAV MANTHAN BHARAT', 'NTC', 'cse', 'ect')";
//        entityManager.createNativeQuery(q394).executeUpdate();
//        String q395 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q395).executeUpdate();
//        String q396 = "VALUES (198, '24270599', 'BADHE VAISHNAVI AMOL', 'Open', 'mech', 'ect')";
//        entityManager.createNativeQuery(q396).executeUpdate();
//        String q397 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q397).executeUpdate();
//        String q398 = "VALUES (199, '24240368', 'DESHMUKH YASH SUNIL', 'OBC', 'cse', 'ect')";
//        entityManager.createNativeQuery(q398).executeUpdate();
//        String q399 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q399).executeUpdate();
//        String q400 = "VALUES (200, '24274757', 'AGARWAL SIDDHANT LALIT', 'Open', 'mech', 'ect')";
//        entityManager.createNativeQuery(q400).executeUpdate();
//        String q401 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q401).executeUpdate();
//        String q402 = "VALUES (201, '24299282', 'NACHAN YASH DNYANDEV', 'NTC', 'cse', 'ect')";
//        entityManager.createNativeQuery(q402).executeUpdate();
//        String q403 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q403).executeUpdate();
//        String q404 = "VALUES (202, '24135557', 'SHINDE HARSHWARDHAN YUVARAJ', 'Open', 'cse', 'aiml')";
//        entityManager.createNativeQuery(q404).executeUpdate();
//        String q405 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q405).executeUpdate();
//        String q406 = "VALUES (203, '24137450', 'SONAWANE PRACHI PRAMOD', 'OBC', 'cse', 'ect')";
//        entityManager.createNativeQuery(q406).executeUpdate();
//        String q407 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q407).executeUpdate();
//        String q408 = "VALUES (204, '24237793', 'ISHAAN SAMEER SARDESHMUKH', 'Open', 'cse', 'ect')";
//        entityManager.createNativeQuery(q408).executeUpdate();
//        String q409 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q409).executeUpdate();
//        String q410 = "VALUES (205, '24214896', 'KARAMBALKAR HARSH JITIN', 'Open', 'cse', 'ect')";
//        entityManager.createNativeQuery(q410).executeUpdate();
//        String q411 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q411).executeUpdate();
//        String q412 = "VALUES (206, '24102844', 'MOHIT VIVEK JAIN', 'Open', 'cse', 'cse')";
//        entityManager.createNativeQuery(q412).executeUpdate();
//        String q413 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q413).executeUpdate();
//        String q414 = "VALUES (207, '24199864', 'PASARE SARVESH DATTATRAY', 'Open', 'cse', 'ect')";
//        entityManager.createNativeQuery(q414).executeUpdate();
//        String q415 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q415).executeUpdate();
//        String q416 = "VALUES (208, '24180326', 'AHUJA KARAN SANJAY', 'Open', 'mech', 'ect')";
//        entityManager.createNativeQuery(q416).executeUpdate();
//        String q417 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q417).executeUpdate();
//        String q418 = "VALUES (209, '24301042', 'LABHSHETWAR SOHAM LAXMIKANT', 'Open', 'cse', 'ect')";
//        entityManager.createNativeQuery(q418).executeUpdate();
//        String q419 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q419).executeUpdate();
//        String q420 = "VALUES (210, '24141405', 'KOTHALKAR YASH ANKUR', 'Open', 'cse', 'ect')";
//        entityManager.createNativeQuery(q420).executeUpdate();
//        String q421 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q421).executeUpdate();
//        String q422 = "VALUES (211, '24115335', 'WAGHMARE JAYESH SANJAY', 'OBC', 'cse', 'ect')";
//        entityManager.createNativeQuery(q422).executeUpdate();
//        String q423 = "INSERT INTO merit_listp12 (Srno, Rollno, cname, Category, prefer1, prefer2)";
//        entityManager.createNativeQuery(q423).executeUpdate();
//        String q424 = "VALUES (212, '24210173', 'PHARTADE DNYANESHWARI ANIL', 'OBC', 'cse', 'ect')";
//        entityManager.createNativeQuery(q424).executeUpdate();




    }
}
